package service

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"instantrepo/internal/domain"
)

type EnvFileManager struct{}

func NewEnvFileManager() *EnvFileManager {
	return &EnvFileManager{}
}

var envLinePattern = regexp.MustCompile(`^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$`)

func (m *EnvFileManager) Prepare(analysis domain.RepositoryAnalysis) (domain.ExecutionResult, error) {
	return m.prepareWithValues(analysis, nil)
}

func (m *EnvFileManager) ApplyValues(analysis domain.RepositoryAnalysis, values map[string]string) (domain.ExecutionResult, error) {
	return m.prepareWithValues(analysis, values)
}

func (m *EnvFileManager) Preview(analysis domain.RepositoryAnalysis) (string, error) {
	if analysis.Env.TargetPath == "" {
		return "", fmt.Errorf("env target path is not available")
	}

	existingValues := readEnvValues(analysis.Env.TargetPath)
	templateLines, err := loadTemplateLines(analysis.Env)
	if err != nil {
		return "", err
	}

	rendered, _ := renderEnvFile(templateLines, existingValues, analysis.Env)
	return rendered, nil
}

func (m *EnvFileManager) WriteRaw(repoPath, targetPath, content string) (domain.ExecutionResult, error) {
	if strings.TrimSpace(targetPath) == "" {
		return domain.ExecutionResult{}, fmt.Errorf("env target path is not available")
	}

	started := time.Now()
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return domain.ExecutionResult{}, fmt.Errorf("create env directory: %w", err)
	}
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		return domain.ExecutionResult{}, fmt.Errorf("write env file: %w", err)
	}

	return domain.ExecutionResult{
		StepID:    "save-env-file",
		Command:   "instantrepo internal:save-env",
		Cwd:       repoPath,
		Stdout:    fmt.Sprintf("Saved %s\n", targetPath),
		Duration:  time.Since(started).String(),
		Succeeded: true,
	}, nil
}

func (m *EnvFileManager) prepareWithValues(analysis domain.RepositoryAnalysis, values map[string]string) (domain.ExecutionResult, error) {
	if analysis.Env.TargetPath == "" && len(analysis.Env.Variables) == 0 {
		return domain.ExecutionResult{}, fmt.Errorf("env target path is not available")
	}

	started := time.Now()

	// Group variables by target dir
	varsByTarget := make(map[string][]domain.EnvVarRequirement)
	for _, item := range analysis.Env.Variables {
		target := item.TargetDir
		if target == "" {
			target = filepath.Dir(analysis.Env.TargetPath)
		}
		varsByTarget[target] = append(varsByTarget[target], item)
	}

	var allStdout []string

	for targetDir, vars := range varsByTarget {
		targetPath := filepath.Join(targetDir, ".env")
		existingValues := readEnvValues(targetPath)
		for key, value := range values {
			trimmed := strings.TrimSpace(value)
			if trimmed == "" {
				continue
			}
			existingValues[key] = trimmed
		}

		// Create a local env config per target
		localEnv := analysis.Env
		localEnv.Variables = vars
		localEnv.TargetPath = targetPath

		// Try to find the template if it existed
		templateLines, _ := loadTemplateLines(localEnv) // Could be empty, handled gracefully

		rendered, summary := renderEnvFile(templateLines, existingValues, localEnv)
		if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
			return domain.ExecutionResult{}, fmt.Errorf("create env directory: %w", err)
		}
		if err := os.WriteFile(targetPath, []byte(rendered), 0o644); err != nil {
			return domain.ExecutionResult{}, fmt.Errorf("write env file: %w", err)
		}
		allStdout = append(allStdout, summary)
	}

	return domain.ExecutionResult{
		StepID:    "create-env-file",
		Command:   "instantrepo internal:prepare-env",
		Cwd:       analysis.RepoPath,
		Stdout:    strings.Join(allStdout, "\n"),
		Duration:  time.Since(started).String(),
		Succeeded: true,
	}, nil
}

func loadTemplateLines(env domain.EnvironmentConfig) ([]string, error) {
	if env.TemplatePath == "" {
		return []string{}, nil
	}

	raw, err := os.ReadFile(env.TemplatePath)
	if err != nil {
		return nil, fmt.Errorf("read env template: %w", err)
	}
	return strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n"), nil
}

func renderEnvFile(templateLines []string, existingValues map[string]string, env domain.EnvironmentConfig) (string, string) {
	var builder strings.Builder
	builder.WriteString("# Generated by InstantRepo. Review unresolved values before running the app.\n")
	builder.WriteString(fmt.Sprintf("# Updated at %s\n\n", time.Now().Format(time.RFC3339)))

	varsByName := map[string]domain.EnvVarRequirement{}
	for _, item := range env.Variables {
		varsByName[item.Name] = item
	}

	seen := map[string]bool{}
	autoFilled := 0
	placeholders := 0
	preserved := 0

	for _, rawLine := range templateLines {
		line := strings.TrimRight(rawLine, "\r")
		matches := envLinePattern.FindStringSubmatch(line)
		if len(matches) != 3 {
			builder.WriteString(line)
			builder.WriteString("\n")
			continue
		}

		name := matches[1]
		templateValue := cleanWriteValue(matches[2])
		item, ok := varsByName[name]
		if !ok {
			builder.WriteString(formatEnvAssignment(name, templateValue))
			builder.WriteString("\n")
			continue
		}

		seen[name] = true
		value, mode := chooseEnvValue(item, existingValues[name], templateValue)
		switch mode {
		case "preserved":
			preserved++
		case "auto":
			autoFilled++
		case "placeholder":
			placeholders++
		}

		writeEnvInstructions(&builder, item, mode)
		builder.WriteString(formatEnvAssignment(name, value))
		builder.WriteString("\n")
	}

	for _, item := range env.Variables {
		if seen[item.Name] {
			continue
		}
		value, mode := chooseEnvValue(item, existingValues[item.Name], "")
		switch mode {
		case "preserved":
			preserved++
		case "auto":
			autoFilled++
		case "placeholder":
			placeholders++
		}

		writeEnvInstructions(&builder, item, mode)
		builder.WriteString(formatEnvAssignment(item.Name, value))
		builder.WriteString("\n")
	}

	summary := fmt.Sprintf(
		"Prepared %s with %d preserved values, %d auto-filled values, and %d placeholders that still need user review.\n",
		env.TargetPath,
		preserved,
		autoFilled,
		placeholders,
	)

	return strings.TrimRight(builder.String(), "\n") + "\n", summary
}

func chooseEnvValue(item domain.EnvVarRequirement, existingValue, templateValue string) (string, string) {
	if strings.TrimSpace(existingValue) != "" {
		return existingValue, "preserved"
	}
	if item.FillStrategy == "configured" && strings.TrimSpace(existingValue) != "" {
		return existingValue, "preserved"
	}
	if item.FillStrategy == "auto_fillable" && strings.TrimSpace(item.SuggestedValue) != "" {
		return item.SuggestedValue, "auto"
	}
	if strings.TrimSpace(templateValue) != "" && item.FillStrategy != "user_required" {
		return templateValue, "template"
	}
	return "", "placeholder"
}

func writeEnvInstructions(builder *strings.Builder, item domain.EnvVarRequirement, mode string) {
	if mode == "preserved" {
		return
	}
	if len(item.Instructions) == 0 && mode != "placeholder" {
		return
	}

	builder.WriteString("\n")
	if mode == "auto" {
		builder.WriteString(fmt.Sprintf("# InstantRepo auto-filled %s.\n", item.Name))
	} else {
		builder.WriteString(fmt.Sprintf("# Action required for %s.\n", item.Name))
	}
	for _, instruction := range item.Instructions {
		builder.WriteString("# ")
		builder.WriteString(instruction)
		builder.WriteString("\n")
	}
}

func formatEnvAssignment(name, value string) string {
	if needsQuoting(value) {
		return fmt.Sprintf("%s=%q", name, value)
	}
	return fmt.Sprintf("%s=%s", name, value)
}

func needsQuoting(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if r == ' ' || r == '#' || r == '"' {
			return true
		}
	}
	return false
}

func cleanWriteValue(value string) string {
	trimmed := strings.TrimSpace(value)
	return strings.Trim(trimmed, `"'`)
}

func readEnvValues(path string) map[string]string {
	values := map[string]string{}
	raw, err := os.ReadFile(path)
	if err != nil {
		return values
	}
	for _, line := range strings.Split(strings.ReplaceAll(string(raw), "\r\n", "\n"), "\n") {
		matches := envLinePattern.FindStringSubmatch(strings.TrimRight(line, "\r"))
		if len(matches) != 3 {
			continue
		}
		values[matches[1]] = cleanWriteValue(matches[2])
	}
	return values
}

func parseEnvAssignments(content string) map[string]string {
	values := map[string]string{}
	for _, line := range strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n") {
		matches := envLinePattern.FindStringSubmatch(strings.TrimRight(line, "\r"))
		if len(matches) != 3 {
			continue
		}
		values[matches[1]] = cleanWriteValue(matches[2])
	}
	return values
}

func relativeEnvTargetPath(repoPath, targetPath string) string {
	relative, err := filepath.Rel(repoPath, targetPath)
	if err != nil {
		return filepath.Base(targetPath)
	}
	return relative
}
