// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeRepository(arg1:string,arg2:string):Promise<domain.AnalyzeResponse>;

export function ExecuteStep(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<domain.ExecuteResponse>;

export function GenerateEnvDraft(arg1:string):Promise<string>;

export function ImportRepository(arg1:string,arg2:string):Promise<domain.AnalyzeResponse>;

export function OpenDirectory():Promise<string>;

export function SaveEnvFile(arg1:string,arg2:string):Promise<domain.ExecuteResponse>;

export function ShellInfo():Promise<Record<string, string>>;
