// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AnalyzeRepository(arg1:string,arg2:string):Promise<domain.AnalyzeResponse>;

export function ApproveEnvVaultEntry(arg1:domain.EnvVaultApproval):Promise<void>;

export function ClonePreflight(arg1:string,arg2:string):Promise<domain.ClonePreflightResponse>;

export function ExecuteStep(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<domain.ExecuteResponse>;

export function ExportRepoDiagnostics(arg1:string):Promise<domain.RepoDiagnosticExport>;

export function GenerateEnvDraft(arg1:string):Promise<domain.EnvDraft>;

export function ImportRepository(arg1:string,arg2:string):Promise<domain.AnalyzeResponse>;

export function InstalledRepoDetails(arg1:number):Promise<domain.InstalledRepoDetailsResponse>;

export function ListInstalledRepos():Promise<domain.InstalledRepoManagerResponse>;

export function MarkEnvVaultEntryStatus(arg1:number,arg2:string):Promise<void>;

export function OpenDirectory():Promise<string>;

export function SaveEnvDraft(arg1:string,arg2:domain.EnvDraft):Promise<domain.ExecuteResponse>;

export function SaveEnvFile(arg1:string,arg2:string):Promise<domain.ExecuteResponse>;

export function SaveEnvVaultCredential(arg1:domain.EnvVaultSaveRequest):Promise<domain.EnvVaultSaveResponse>;

export function ShellInfo():Promise<Record<string, string>>;

export function SuppressEnvVaultPrompt(arg1:domain.EnvVaultPromptSuppression):Promise<void>;
