// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIEnvReviewSettings() {
  return window['go']['main']['App']['AIEnvReviewSettings']();
}

export function AnalyzeRepository(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeRepository'](arg1, arg2);
}

export function ApproveEnvVaultEntry(arg1) {
  return window['go']['main']['App']['ApproveEnvVaultEntry'](arg1);
}

export function ClearEnvContributionQueue() {
  return window['go']['main']['App']['ClearEnvContributionQueue']();
}

export function ClonePreflight(arg1, arg2) {
  return window['go']['main']['App']['ClonePreflight'](arg1, arg2);
}

export function EnvContributionSettings() {
  return window['go']['main']['App']['EnvContributionSettings']();
}

export function ExecuteStep(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteStep'](arg1, arg2, arg3, arg4);
}

export function ExportRepoDiagnostics(arg1) {
  return window['go']['main']['App']['ExportRepoDiagnostics'](arg1);
}

export function GenerateEnvDraft(arg1) {
  return window['go']['main']['App']['GenerateEnvDraft'](arg1);
}

export function ImportRepository(arg1, arg2) {
  return window['go']['main']['App']['ImportRepository'](arg1, arg2);
}

export function InstalledRepoDetails(arg1) {
  return window['go']['main']['App']['InstalledRepoDetails'](arg1);
}

export function ListEnvVaultEntries() {
  return window['go']['main']['App']['ListEnvVaultEntries']();
}

export function ListInstalledRepos() {
  return window['go']['main']['App']['ListInstalledRepos']();
}

export function MarkEnvVaultEntryStatus(arg1, arg2) {
  return window['go']['main']['App']['MarkEnvVaultEntryStatus'](arg1, arg2);
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function RecordEnvContributionConsent(arg1) {
  return window['go']['main']['App']['RecordEnvContributionConsent'](arg1);
}

export function RemoveEnvVaultEntry(arg1) {
  return window['go']['main']['App']['RemoveEnvVaultEntry'](arg1);
}

export function RevealEnvVaultEntry(arg1) {
  return window['go']['main']['App']['RevealEnvVaultEntry'](arg1);
}

export function RevokeEnvVaultApproval(arg1) {
  return window['go']['main']['App']['RevokeEnvVaultApproval'](arg1);
}

export function SaveAIEnvReviewSettings(arg1) {
  return window['go']['main']['App']['SaveAIEnvReviewSettings'](arg1);
}

export function SaveEnvContributionSettings(arg1) {
  return window['go']['main']['App']['SaveEnvContributionSettings'](arg1);
}

export function SaveEnvDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvDraft'](arg1, arg2);
}

export function SaveEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvFile'](arg1, arg2);
}

export function SaveEnvVaultCredential(arg1) {
  return window['go']['main']['App']['SaveEnvVaultCredential'](arg1);
}

export function ShellInfo() {
  return window['go']['main']['App']['ShellInfo']();
}

export function SuppressEnvVaultPrompt(arg1) {
  return window['go']['main']['App']['SuppressEnvVaultPrompt'](arg1);
}

export function UpdateEnvVaultEntry(arg1) {
  return window['go']['main']['App']['UpdateEnvVaultEntry'](arg1);
}
