// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeRepository(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeRepository'](arg1, arg2);
}

export function ClonePreflight(arg1, arg2) {
  return window['go']['main']['App']['ClonePreflight'](arg1, arg2);
}

export function ExecuteStep(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteStep'](arg1, arg2, arg3, arg4);
}

export function ExportRepoDiagnostics(arg1) {
  return window['go']['main']['App']['ExportRepoDiagnostics'](arg1);
}

export function GenerateEnvDraft(arg1) {
  return window['go']['main']['App']['GenerateEnvDraft'](arg1);
}

export function ImportRepository(arg1, arg2) {
  return window['go']['main']['App']['ImportRepository'](arg1, arg2);
}

export function InstalledRepoDetails(arg1) {
  return window['go']['main']['App']['InstalledRepoDetails'](arg1);
}

export function ListInstalledRepos() {
  return window['go']['main']['App']['ListInstalledRepos']();
}

export function OpenDirectory() {
  return window['go']['main']['App']['OpenDirectory']();
}

export function SaveEnvFile(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvFile'](arg1, arg2);
}

export function ShellInfo() {
  return window['go']['main']['App']['ShellInfo']();
}
